export const CustomersFakeData: ITableData[] = [
  {
    customerId: 1455558999,
    name: 'Cupcake',
    middleName: 'Khachatryan',
    lastName: 'Harrison',
    address: 'Yerevan Armenia',
    email: 'gorkhach@gmail.com',
    status: 'Terminated',
  },
  {
    customerId: 7854449554,
    name: 'Donut',
    middleName: 'Harutyunyan',
    lastName: 'Harrison',
    address: 'Yerevan Armenia',
    email: 'gorkhach@gmail.com',
    status: 'Verifiyed',
  },
  {
    customerId: 1258964789,
    name: 'Eclair',
    middleName: 'Vardanyankggkgkggkiugkugkiugkug',
    lastName: 'Harrison',
    address: 'Yerevan Armenia',
    email: 'gorkhach@gmail.com',
    status: 'pending',
  },
  {
    customerId: 4589652368,
    name: 'Frozen',
    middleName: 'Gevorgyan',
    lastName: 'Harrison',
    address: 'Yerevan Armenia',
    email: 'gorkhach@gmail.com',
    status: 'Terminated',
  },
  {
    customerId: 4587965287,
    name: 'Gingerbread',
    middleName: 'jeremih',
    lastName: 'Harrison',
    address: 'Yerevan Armenia',
    email: 'gorkhach@gmail.com',
    status: 'Terminated',
  },
  {
    customerId: 2365897415,
    name: 'Honeycomb',
    middleName: 'Smit',
    lastName: 'Harrison',
    address: 'Yerevan Armenia',
    email: 'gorkhach@gmail.com',
    status: 'Terminated',
  },
  {
    customerId: 3215897458,
    name: 'Ice cream sandwich',
    middleName: 'Omar',
    lastName: 'Harrison',
    address: 'Yerevan Armenia',
    email: 'gorkhach@gmail.com',
    status: 'Verifiyed',
  },
  {
    customerId: 5698547821,
    name: 'Jelly Bean',
    middleName: 'Carter',
    lastName: 'Harrison',
    address: 'Yerevan Armenia',
    email: 'gorkhach@gmail.com',
    status: 'Verifiyed',
  },
  {
    customerId: 6548791236,
    name: 'KitKat',
    middleName: 'Willson',
    lastName: 'Harrison',
    address: 'Yerevan Armenia',
    email: 'gorkhach@gmail.com',
    status: 'pending',
  },
  {
    customerId: 5487963214,
    name: 'Lollipop',
    middleName: 'Brook',
    lastName: 'Harrison',
    address: 'Yerevan Armenia',
    email: 'gorkhach@gmail.com',
    status: 'Verifiyed',
  },
  {
    customerId: 5897410236,
    name: 'Marshmallow',
    middleName: 'Lizz',
    lastName: 'Harrison',
    address: 'Yerevan Armenia',
    email: 'gorkhach@gmail.com',
    status: 'Terminated',
  },
  {
    customerId: 9658741256,
    name: 'Nougat',
    middleName: 'Morris',
    lastName: 'Harrison',
    address: 'Yerevan Armenia',
    email: 'gorkhach@gmail.com',
    status: 'Terminated',
  },
  {
    customerId: 9875412589,
    name: 'Oreo',
    middleName: 'Johnson',
    lastName: 'Harrison',
    address: 'Yerevan Armenia',
    email: 'gorkhach@gmail.com',
    status: 'pending',
  },
];
